version: '2'

services:
  db-svc:
    image: postgres:9.5
    container_name: db-svc
    networks:
      - dev
    ports:
      - 9999:5432
    environment:
      - POSTGRES_USER=goo
      - POSTGRES_PASSWORD=goo
      - POSTGRES_DB=goo

  test:
    image: flowup/godev
    volumes:
      - .:/go/src/github.com/Harticon/DBproj
    working_dir: /go/src/github.com/Harticon/DBproj
    networks:
      - dev
    ports:
      - 8080:8080
    depends_on:
      - db-svc
    restart: always
    command: goconvey -timeout 60s -host 0.0.0.0



networks:
  dev:



